### ISSUE TITLE
[Suggestions] Need To Improve

### ISSUE THREAD

**Issue by faizmodan** [gosimulate/gosimulator#29]
App need more slower then it is and if you can add human like walk,and some time if error occurred as something went wrong while walking, some'''' while catching pokemon or pokestop it is become to aggressive and run faster so it will also cause softban and other thing is that you can set remember last location as some routes like Disney land , santa monica new york south etc.... If we will far from last location and stop and start again i will definitely give soft ban 

I wish you will pay attention on it as many ppl are using there main acc on simulator including me

**Comment by gosimulate** [comment]
Solved in latest release

**Comment by faizmodan** [comment]
App need to have pause button and remember last location, mostly after app started still shows starting not show stop button and if we press stop button it will still running so it is not safe if we forget to force stop it,and start po'go
